---
- name:  Install the latest version of 
  hosts: all
  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: present

   
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

