---
- name:  Install the latest version of httpd packages
  hosts: all
  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: installed

   
  - name: Start service httpd, if not started
    service:
      name: httpd
      state: started

  - name: reboot of the computer
    reboot:  

